repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    args:
    - --maxkb=100
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    exclude: |
      (?x)(
        ^CODE_OF_CONDUCT\.md$|
        ^chart\/README\.md$
      )
    types_or:
    - markdown
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.11.5
  hooks:
  - id: isort
- repo: https://github.com/adrienverge/yamllint
  rev: v1.31.0
  hooks:
  - id: yamllint
    args:
    - --config-file=.yamllintrc.yaml
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-docstrings
    - pep8-naming
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
  - id: mypy
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
  - id: helm-docs-built
    args:
    - --chart-search-root=chart
    - --sort-values-order=file
